---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  namespace: myns
  labels:
    app: bgg
    name: app-deploy

spec:
  # num of instances
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  # select pods belonging to this deployment
  selector:
    matchLabels:
      app: bgg
      name: app-po

  # pod template
  template:
    metadata:
      name: app-po
      labels:
        app: bgg
        name: app-po
    spec:
      containers:
      - name: app-container
        image: stackupiss/bgg-backend:v1
        imagePullPolicy: IfNotPresent
        envFrom:
        - ConfigMapRef:
          name: bgg-cm
        - secretRef:
          name: app-secret
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  labels:
    app: bgg
    name: app-svc
spec:
  type: LoadBalancer
  selector:
    app: bgg
    name: app-po
  ports:
  - port: 80
    targetPort: 3000
