---
apiVersion: v1
kind: ConfigMap
metadata:
  name: code-server-cm
  namespace: w3-ns
  labels:
    app: code-server
    name: code-server-cm
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: code-144.126.242.179.nip.io

---
apiVersion: v1
kind: Secret
metadata:
  name: code-server-secret
  namespace: w3-ns
  labels:
    app: code-server
    name: code-server-secret
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ=
  SUDO_PASSWORD: cGFzc3dvcmQ=