---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dov-cm
  namespace: myns
  labels:
    app: dov
    name: dov-cm
data:
  app_name: 'My Dov Bear'

---
apiVersion: v1
kind: Secret
metadata:
  name: dov-secret
  namespace: myns
  labels:
    app: dov
    name: dov-secret
type: Opaque
data:
  app_instance: c2VjcmV0