---
apiVersion: v1
kind: Namespace
metadata:
  name: myns
  labels:
    app: bgg

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgg-cm
  namespace: myns
  labels:
    app: bgg
    name: bgg-cm
data:
  BGG_DB_USER: root
  BGG_DB_HOST: db-svc.myns.svc.cluster.local

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: myns
  labels:
    app: bgg
    name: app-secret
type: Opaque
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=